### ISSUE TITLE
Rename module to Kalagraphs

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalaponents#22]
How did we not think of this before?

**Comment by RobLoach** [comment]
:+1:

**Comment by soniktrooth** [comment]
two votes makes it unanimous

**Comment by hawkeyetwolf** [comment]
I think Kalaparagraphs would be better than Kalagraphs. When I first saw it I thought it was a graphing library.

**Comment by soniktrooth** [comment]
Wait, I've go it: 

Paramunagraphs

**Comment by RobLoach** [comment]
Comunaph
