### ISSUE TITLE
Move autogrow to a separate module

### ISSUE THREAD

**Issue by hawkeyetwolf** [kalamuna/kalaponents#54]
See [Best practices for handling external libraries in Drupal 8](https://www.drupal.org/node/2605130):
1. Instead of hotlinking to CDNjs, just provide the link on the module page.
1. Then, in `hook_install()`, check that the developer downloaded it to `DRUPAL_ROOT/libraries`.

Since the [autogrow](https://www.drupal.org/project/autogrow) module namespace is taken (for the CKEditor plugin), let's use `autogrow_textarea`.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/jquery_ns_autogrow

- [x] Rename the module to autogrow_textarea
- [ ] hook_install will only check on install, having acheck in status report page would be more persistent

Moved them to individual stories in the issue queue: https://github.com/kalamuna/jquery_ns_autogrow/issues

**Comment by RobLoach** [comment]
Taking myself off of this for now, as there are other things on the board. The [initial module](https://github.com/kalamuna/jquery_ns_autogrow) is there, outlined some follow ups in the above comment.

**Comment by gremy** [comment]
@RobLoach I think a better solution is to use composer to install the library automatically for you.
I also updated README.me with instructions to add the package in the composer.json repositories.
And using composer, you are not even able to install the module without the library.

**Comment by gremy** [comment]
@RobLoach should we close this issue, and keep track of issues on the autogrow_textarea repo?

**Comment by hawkeyetwolf** [comment]
@gremy, not everyone uses composer to manage their dependencies right now. Maybe in the future, everyone will have to, though?

**Comment by gremy** [comment]
I'll update the readme a bit more for non-composer folks. And also do the check for status report.

**Comment by hawkeyetwolf** [comment]
On second thought: Yes, let's add the composer dependency. But we also still need the other logic to alert users to download it if it's missing.

**Comment by gremy** [comment]
@derekderaps many improvements happened:
https://github.com/kalamuna/autogrow_textarea/pull/4

**Comment by hawkeyetwolf** [comment]
Most excellent work, Mr. @gremy! Closing issue.
